version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    image: web_app:latest
    ports:
      - '80:80'
    command: python manage.py run -h 0.0.0.0 -p 80
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    depends_on:
      - redis

  worker:
    image: web_app:latest
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    depends_on:
      - web
      - redis

  redis:
    image: redis:5.0.5-alpine

  dashboard:
    build: ./project/dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '9181:9181'
    command: rq-dashboard -H redis
