version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    image: web_app:latest
    ports:
      - '80:80'
    command: python manage.py run -h 0.0.0.0 -p 80
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig

